FROM eclipse-temurin:17-jdk-jammy AS build
COPY . .
RUN ./mvnw -B package

FROM eclipse-temurin:17-jre-jammy
COPY --from=build target/*.jar config-server-1.0.0.jar
EXPOSE 9101
ENTRYPOINT ["java", "-jar", "config-server-1.0.0.jar"]
