FROM eclipse-temurin:17-jdk-jammy AS build
COPY . .
RUN ./mvnw -B package -DskipTests

FROM eclipse-temurin:17-jre-jammy
COPY --from=build target/*.jar ms-patient-1.0.0.jar
EXPOSE 9003
ENTRYPOINT ["java", "-jar", "ms-patient-1.0.0.jar"]
